name: i
description: A Dart library for representing and performing arithmetic operations with complex numbers.
version: 1.0.0
repository: https://github.com/xooniverse/i

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

topics:
  - math
  - complex
  - numbers